services:
  user-db:
    image: 'postgres:16'
    container_name: user-service-postgres
    environment:
      - 'POSTGRES_DB=user_db'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=root123'
    ports:
      - "5433:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data

  driver-db:
    image: 'postgres:16'
    container_name: driver-service-postgres
    environment:
      - 'POSTGRES_DB=driver_db'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=root123'
    ports:
      - "5434:5432"
    volumes:
      - driver_postgres_data:/var/lib/postgresql/data

  redis:
    image: 'redis:7'
    container_name: location-service-redis
    ports:
      - "6379:6379"

  pricing-db:
    image: 'postgres:16'
    container_name: pricing-service-postgres
    environment:
      - 'POSTGRES_DB=pricing_db'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=root123'
    ports:
      - "5435:5432"
    volumes:
      - pricing_postgres_data:/var/lib/postgresql/data

  trip-db:
    image: 'postgres:16'
    container_name: trip-service-postgres
    environment:
      - 'POSTGRES_DB=trip_db'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=root123'
    ports:
      - "5436:5432"
    volumes:
      - trip_postgres_data:/var/lib/postgresql/data

  dispatch-db:
    image: 'postgres:16'
    container_name: dispatch-service-postgres
    environment:
      - 'POSTGRES_DB=dispatch_db'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=root123'
    ports:
      - "5437:5432"
    volumes:
      - dispatch_postgres_data:/var/lib/postgresql/data

volumes:
  user_postgres_data:
  driver_postgres_data:
  pricing_postgres_data:
  trip_postgres_data:
  dispatch_postgres_data: