spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/driver_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true

server:
  port: 8081
